#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\HomeController::home
product:
  path: /product/{id}
  controller: App\Controller\HomeController::product
addtocart:
  path: /addtocart
  controller: App\Controller\HomeController::addProductToCart
error:
  path: /error
  controller: App\Controller\HomeController::error
cart:
  path: /cart
  controller: App\Controller\HomeController::cart